-- dont damage cops/civs by explosions generated by the flashbang trap
local orig_explosion_manager_damage_characters = ExplosionManager._damage_characters
Hooks:OverrideFunction(ExplosionManager, "_damage_characters", function (self, detect_results, params, variant, damage_func_name)
	DS_BW.explosive_trap_ids = DS_BW.explosive_trap_ids or {}
	if DS_BW._creating_explosive_flashbang_trap and DS_BW.explosive_trap_ids[params.ignore_unit:id()] then
		DS_BW._creating_explosive_flashbang_trap = nil
		local results = {
			count_cops = 0,
			count_gangsters = 0,
			count_civilians = 0,
			count_criminals = 0,
			count_cop_kills = 0,
			count_gangster_kills = 0,
			count_civilian_kills = 0,
			count_criminal_kills = 0
		}
		return results
	else
		return orig_explosion_manager_damage_characters(self, detect_results, params, variant, damage_func_name)
	end
end)